services:
  message_queue:
    build: ./src/message_queue
    ports:
      - "8100:8100"
    environment:
      - MESSAGE_QUEUE_HOST=message_queue
      - MESSAGE_QUEUE_PORT=8100
    networks:
      - ragapp-network

  control_plane:
    build: ./src/control_plane
    ports:
      - "8000:8000"
    environment:
      - HOST=control_plane
      - PORT=8000
      - MESSAGE_QUEUE_URL=http://message_queue:8100
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL=gpt-3.5-turbo
      - ORCHESTRATOR_TYPE=agent
    networks:
      - ragapp-network
    depends_on:
      - message_queue

  travel_agent:
    build: .
    configs:
      - source: travel_agent_tools_config
        target: /app/config/tools.yaml
    environment:
      - AGENT=true
      - CONTROL_PLANE_URL=http://control_plane:8000
      - MESSAGE_QUEUE_URL=http://message_queue:8100
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=dev
      - DESCRIPTION=I can use DuckDuckGo search to find information about a country.
      - SYSTEM_PROMPT=You're a helpful travel agent, your task is use DuckDuckGo search to find information about a country. You just need to return the information you find.
    depends_on:
      - control_plane
      - message_queue
    networks:
      - ragapp-network

  research_agent:
    build: .
    configs:
      - source: research_agent_tools_config
        target: /app/config/tools.yaml
    environment:
      - AGENT=true
      - CONTROL_PLANE_URL=http://control_plane:8000
      - MESSAGE_QUEUE_URL=http://message_queue:8100
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENVIRONMENT=dev
      - DESCRIPTION=I can help you make a plan for your trip and give you some tips on where to go.
      - SYSTEM_PROMPT=You are a smart assistant, you can answer using no additional tools. Use the provided information to help the user plan their trip.
    depends_on:
      - control_plane
      - message_queue
    networks:
      - ragapp-network

configs:
  travel_agent_tools_config:
    content: |
      llamahub: {}
      local:
        duckduckgo: {}
  research_agent_tools_config:
    content: |
      llamahub: {}
      local: {}

networks:
  ragapp-network:
    driver: bridge